//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMenu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMenu.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About FMenu.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers:.
        /// </summary>
        public static string about_developers {
            get {
                return ResourceManager.GetString("about_developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about_header {
            get {
                return ResourceManager.GetString("about_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta-Testers:.
        /// </summary>
        public static string about_testers {
            get {
                return ResourceManager.GetString("about_testers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string about_version {
            get {
                return ResourceManager.GetString("about_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Menu.
        /// </summary>
        public static string buildmenu {
            get {
                return ResourceManager.GetString("buildmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capsule.
        /// </summary>
        public static string buildmenu_capsule {
            get {
                return ResourceManager.GetString("buildmenu_capsule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube.
        /// </summary>
        public static string buildmenu_cube {
            get {
                return ResourceManager.GetString("buildmenu_cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder.
        /// </summary>
        public static string buildmenu_cylinder {
            get {
                return ResourceManager.GetString("buildmenu_cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Menu.
        /// </summary>
        public static string buildmenu_header {
            get {
                return ResourceManager.GetString("buildmenu_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane.
        /// </summary>
        public static string buildmenu_plane {
            get {
                return ResourceManager.GetString("buildmenu_plane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere.
        /// </summary>
        public static string buildmenu_sphere {
            get {
                return ResourceManager.GetString("buildmenu_sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an object and press X.
        /// </summary>
        public static string buildmenu_text1 {
            get {
                return ResourceManager.GetString("buildmenu_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected object:.
        /// </summary>
        public static string buildmenu_text2 {
            get {
                return ResourceManager.GetString("buildmenu_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Fireworks.
        /// </summary>
        public static string fireworksspawn {
            get {
                return ResourceManager.GetString("fireworksspawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn Special Fireworks.
        /// </summary>
        public static string fireworksspawn_header {
            get {
                return ResourceManager.GetString("fireworksspawn_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tim.
        /// </summary>
        public static string fireworksspawn_tim {
            get {
                return ResourceManager.GetString("fireworksspawn_tim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string mods {
            get {
                return ResourceManager.GetString("mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoclicker.
        /// </summary>
        public static string mods_autoclicker {
            get {
                return ResourceManager.GetString("mods_autoclicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string mods_header {
            get {
                return ResourceManager.GetString("mods_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string movement {
            get {
                return ResourceManager.GetString("movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fly.
        /// </summary>
        public static string movement_fly {
            get {
                return ResourceManager.GetString("movement_fly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string movement_header {
            get {
                return ResourceManager.GetString("movement_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoClip.
        /// </summary>
        public static string movement_noclip {
            get {
                return ResourceManager.GetString("movement_noclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings_header {
            get {
                return ResourceManager.GetString("settings_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Language.
        /// </summary>
        public static string settings_language {
            get {
                return ResourceManager.GetString("settings_language", resourceCulture);
            }
        }
    }
}
